# -*- coding: utf-8 -*-
"""
Created on Sat Aug 25 00:48:35 2018

@author: Chris Clement
"""

import numpy
import pickle

class stadium():
    '''
    This is the class we use to hold the stadium objects we create with all
    their data and we can reference back to it because it's in the initial
    game statement.
    '''
    
    def __init__(self, name, city, province, home_teams, surface, capacity, GPS, orientation, elevation, airport, full_end_zones, TZCode, isDome):
        self.name = name  # Name of the stadium
        self.city = city  # City in which the stadium is located
        self.province = province  # Province in which the stadium is located
        self.home_teams = home_teams  # List of the teams that call this stadium home
        self.surface = surface  # Natural v turf and type of turf. TODO: Consider swapping this for a boolean "isNatural"
        self.capacity = capacity  # Seating capacity of the stadium, often approx due to renovations, etc.
        self.GPS = GPS  # Lat/Long of midfield, we could stand to cut down one decimal point but w/e
        self.orientation = orientation  # True bearing orientation of the long axis of the field, using the more northerly angle
        self.elevation = elevation  # Elevation above sea level in m
        self.airport = airport  # Gives the nearest airport code to use the proper METAR data
        self.full_end_zones = full_end_zones  # True if the end zones are full sized, false if they are cut off (not full length, corners cut bc of track, etc.
        self.TZCode = TZCode  # Gives the appropriate code to handle time zones
        self.isDome = isDome  # True if it's a domed stadium
        return None

stadium_list =\
[['Oland Stadium', 'Antigonish', 'NS', ['SFX'], 'FieldTurf', 4000, [45.616639, -61.994972], 359, 195, 'CYYG', False, "America/Halifax", False],
 ['Huskies Stadium', 'Halifax', 'NS', ['SMU'], 'FieldTurf', 5000, [44.631111, -63.579556], 343, 23, 'CYHZ', False, "America/Halifax", False],
 ['Raymond Field', 'Wolfville', 'NS', ['ACA'], 'FieldTurf', 3000, [45.092000, -64.367444], 346, 8, 'CYHZ', False, "America/Halifax", False],
 ['MacAulay Field', 'Sackville', 'NB', ['MTA'], 'Natural Grass', 2500, [45.897750, -64.373389], 281, 18, 'CYQM', False, "America/Halifax", False],
 ['Coulter Field', 'Lennoxville', 'QC', ['BIS'], 'FieldTurf', 2200, [45.365222, -71.841194], 0, 148, 'CYSC', True, "America/Toronto", False],
 ["Stade de l'Universite", 'Sherbrooke', 'QC', ['SHE'], '', 3359, [45.374583, -71.930778], 271, 252, 'CYSC', False, "America/Toronto", False],
 ['CEPSUM', 'Montreal', 'QC', ['MON'], '', 5100, [45.509083, -73.611472], 32, 133, 'CYUL', True, "America/Toronto", False],
 ['Concordia Stadium', 'Montreal', 'QC', ['CON'], 'FieldTurf', 4000, [45.457972, -73.63747], 39, 54, 'CYUL', True, "America/Toronto", False],
 ['Percival Molson Stadium', 'Montreal', 'QC', ['MCG, ALS'], 'FieldTurf', 23420, [45.510111, -73.580889], 10, 66, 'CYUL', False, "America/Toronto", False],
 ['Stade TELUS', 'Quebec', 'QC', ['LAV'], 'FieldTurf', 12817, [46.783722, -71.279611], 321, 81, 'CYQB', False, "America/Toronto", False],
 ['MNP Park', 'Ottawa', 'ON', ['CAR'], 'FieldTurf', '3500', [45.388583, -75.694194], 337, 64, 'CYOW', True, "America/Toronto", False],
 ['Gee-Gees Field', 'Ottawa', 'ON', ['OTT'], 'FieldTurf', 3000, [45.416056, -75.665194], 88, 61, 'CYOW', False, "America/Toronto", False],
 ['Old Richardson Memorial Stadium', 'Kingston', 'ON', ['QUE'], 'Natural Grass', 8000, [44.227639, -76.516333], 356, 93, 'CYGK', False, "America/Toronto", False],
 ['New Richardson Memorial Stadium', 'Kingston', 'ON', ['QUE'], 'FieldTurf', 8000, [44.227639, -76.516333], 356, 93, 'CYGK', True, "America/Toronto", False],
 ['Varsity Stadium', 'Toronto', 'ON', ['TOR'], 'Polytan Ligaturf', 5000, [43.667056, -79.397278], 344, 111, 'CYTZ', False, "America/Toronto", False],
 ['York Lions Stadium', 'Toronto', 'ON', ['YRK'], 'FieldTurf', 3700, [43.776417, -79.511972], 345, 199, 'CYYZ', True, "America/Toronto", False],
 ['Ron Joyce Stadium', 'Hamilton', 'ON', ['MAC'], 'FieldTurf', 6000, [43.266056, -79.917028], 358, 90, 'CYHM', True, "America/Toronto", False],
 ['Guelph Alumni Stadium', 'Guelph', 'ON', ['GUE'], 'FieldTurf Revolution', 8500, [43.535056, -80.226583], 317, 336, 'CYYZ', False, "America/Toronto", False],
 ['Warrior Field', 'Waterloo', 'ON', ['WAT'], 'FieldTruf Duraspin PRO', 5400, [43.474250, -80.549694], 64, 342, 'CYKF', True, "America/Toronto", False],
 ['University Stadium', 'Waterloo', 'ON', ['WLU'], 'FieldTurf', 6000, [43.470194, -80.53013], 63, 332, 'CYKF', False, "America/Toronto", False],
 ['TD Waterhouse Stadium', 'London', 'ON', ['WES'], 'FieldTurf', 8000, [42.999889, -81.273833], 8, 249, 'CYXU', False, "America/Toronto", False],
 ['University of Windsor Stadium', 'Windsor', 'ON', ['WIN'], 'FieldTurf', 2000, [42.298222, -83.063000], 8, 180, 'CYQG', False, "America/Toronto", False],
 ['Investors Group Field', 'Winnipeg', 'MB', ['MAN, BBO'], 'FieldTurf', 33500, [49.807833, -97.143000], 0, 227, 'CYWG', True, "America/Winnipeg", False],
 ['University of Manitoba Stadium', 'Winnipeg', 'MB', ['MAN'], 'Natural Grass', 5000, [49.806750, -97.146222], 332, 227, 'CYWG', False, "America/Winnipeg", False],
 ['Griffiths Stadium', 'Saskatoon', 'SK', ['SKH'], 'FieldTurf', 6171, [52.127083, -106.629833], 355, 502, 'CYXE', False, "America/Regina", False],
 ['Mosaic Stadium', 'Regina', 'SK', ['REG, RRI'], 'FieldTurf', 33427, [50.450528, -104.633083], 355, 576, 'CYQR', True, "America/Regina", False],
 ['Mosaic Stadium at Taylor Field', 'Regina', 'SK', ['REG, RRI'], 'FieldTurf', 33350, [50.452639, -104.624222], 315, 576, 'CYQR', True, "America/Regina", False],
 ['McMahon Stadium', 'Calgary', 'AB', ['CGY, STA'], 'FieldTurf', 33650, [51.070389, -114.121472], 335, 1099, 'CYYC', True, "America/Edmonton", False],
 ['Foote Field', 'Edmonton', 'AB', ['ALB'], 'PureGrass', 3500, [53.503528, -113.530472], 0, 669, 'CYEG', True, "America/Edmonton", False],
 ['Thunderbird Stadium', 'Vancouver', 'BC', ['UBC'], 'PolyTan Turf', 3411, [49.254417, -123.245556], 331, 79, 'CYVR', True, "America/Vancouver", False],
 ['Swangard Stadium', 'Burnaby', 'BC', ['SFU'], 'Natural Grass', 5288, [49.278639, -122.922278], 103, 323, 'CYVR', True, "America/Vancouver", False],
 ['TD Place', 'Ottawa', 'ON', ['RED'], 'FieldTurf', 24000, [45.398194, -75.683472], 60, 63, 'CYOW', True, "America/Toronto", False],
 ['Setters Place', 'Red Deer', 'AB', [], 'Natural Grass', 500, [52.268028, -113.833472], 0, 855, 'CYQF', False, "America/Edmonton", False],
 ['Westhills Stadium', 'Victoria', 'BC', ['VIR'], 'FieldTurf', 1718, [48.443083, -123.523611], 274, 69, 'CYYJ', True, "America/Vancouver", False],
 ['Rogers Centre', 'Toronto', 'ON', ['ARG'], 'AstroTurf', 53506, [43.641500, -79.389139], 345, 79, 'CYYZ', True, "America/Toronto", False],
 ['Commonwealth Stadium', 'Edmonton', 'AB', ['ESK'], 'Shaw Sports Turf', 56302,  [53.559611, -113.476167], 0, 657, 'CYEG', False, "America/Edmonton", False],
 ['BMO Stadium', 'Toronto', 'ON', ['ARG'], 'Natural Grass', 30991, [43.633222, -79.418583], 344, 83, 'CYTZ', True, "America/Toronto", False],
 ['Olympic Stadium', 'Montreal', 'QC', ['ALS'], 'FieldTurf', 56040, [45.557917, -73.551500], 350, 27, 'CYUL', True, "America/Toronto", False],
 ['BC Place', 'Vancouver', 'BC', ['LNS'], 'FieldTurf', 54320, [49.276639, -123.111861], 54, 8, 'CYVR', True, "America/Vancouver", False],
 ['Tim Hortons Field', 'Hamiton', 'ON', ['TIC'], 'FieldTurf', 24000, [43.252111, -79.830083], 305, 85, 'CYHM', True, "America/Toronto", False],
 ['Moncton Stadium', 'Moncton', 'NB', [], 'FieldTurf', 10000, [46.108528, -64.78350], 29, 18, 'CYQM', False, "America/Halifax", False],
 ['Ivor Wynne Stadium', 'Hamilton', 'ON', ['TIC'], 'AstroPlay', 29600, [43.252111, -79.830083], 107, 85, 'CYHM', True, "America/Toronto", False],
 ['CanadInns Stadium', 'Winnipeg', 'MB', ['BBO'], 'AstroPlay', 29533, [49.890120, -97.197260], 4, 231, 'CYWG', True, "America/Winnipeg", False]]

stadia = {x[0] : stadium(*x) for x in stadium_list}

class team():
  __name__ = "team"

  def __init__(self, name, long_name, season_conferences):
    self.name = name  # 3 letter form of the team name, e.g. "MAN"
    self.long_name = long_name  # Full name of the school, e.g. "University of Manitoba"
    self.season_conferences = season_conferences  # A dict of seasons and conferences, e.g. 2002:"CWUAA", 2003:"CWUAA", 2004:"CWUAA"...
    self.gamelist = []  # A list holding all their games
    self.losses_wins = [0, 0]  # LOSSES THEN WINS bc of False/True being analogous to 0/1

  def create_gamelist(self):
    self.gamelist = [game for game in Globals.gamelist if self in game.AWAY_HOME]
  
  def calculate_losses_wins(self):
    for game in self.gamelist:
      self.losses_wins[game.AWAY_HOME.index(self) == game.home_win] += 1


team_list =\
[["ACA", "Acadia University", {season:"AUS" for season in range(2002, 2020)}],
 ["SMU", "Saint Mary's University", {season:"AUS" for season in range(2002, 2020)}],
 ["SFX", "St Francis Xavier University", {season:"AUS" for season in range(2002, 2020)}],
 ["MTA", "Mount Allison University", {season:"AUS" for season in range(2002, 2020)}],
 ["BIS", "Bishop's University", {**{season:"RSEQ" for season in range(2002, 2017)},  **{season:"AUS" for season in range(2017, 2020)}}],
 ["SHE", "Universite de Sherbrooke", {season:"RSEQ" for season in range(2003, 2020)}],
 ["LAV", "Universite de Laval", {season:"RSEQ" for season in range(2002, 2020)}],
 ["MON", "Universite de Montreal", {season:"RSEQ" for season in range(2002, 2020)}],
 ["CON", "Concordia University", {season:"RSEQ" for season in range(2002, 2020)}],
 ["MCG", "McGill University", {season:"RSEQ" for season in range(2002, 2020)}],
 ["CAR", "Carleton University", {season:"OUA" for season in range(2013, 2020)}],
 ["OTT", "University of Ottawa", {season:"OUA" for season in range(2002, 2020)}],
 ["QUE", "Queen's University", {season:"OUA" for season in range(2002, 2020)}],
 ["TOR", "University of Toronto", {season:"OUA" for season in range(2002, 2020)}],
 ["YRK", "York University", {season:"OUA" for season in range(2002, 2020)}],
 ["MAC", "McMaster University", {season:"OUA" for season in range(2002, 2020)}],
 ["GUE", "Guelph University", {season:"OUA" for season in range(2002, 2020)}],
 ["WAT", "University of Waterloo", {season:"OUA" for season in range(2002, 2020)}],
 ["WLU", "Wilfrid Laurier University", {season:"OUA" for season in range(2002, 2020)}],
 ["WES", "University of Western Ontarion", {season:"OUA" for season in range(2002, 2020)}],
 ["WIN", "University of Windsor", {season:"OUA" for season in range(2002, 2020)}],
 ["MAN", "University of Manitoba", {season:"CWUAA" for season in range(2002, 2020)}],
 ["REG", "University of Regina", {season:"CWUAA" for season in range(2002, 2020)}],
 ["SKH", "University of Saskatchewan", {season:"CWUAA" for season in range(2002, 2020)}],
 ["ALB", "University of Alberta", {season:"CWUAA" for season in range(2002, 2020)}],
 ["CGY", "University of Calgary", {season:"CWUAA" for season in range(2002, 2020)}],
 ["UBC", "University of British Columbia", {season:"CWUAA" for season in range(2002, 2020)}],
 ["SFU", "Simon Fraser University", {season:"CWUAA" for season in range(2002, 2010)}]]

teams = {x[0]:team(*x) for x in team_list}

class scoring_play():
    '''
    Let's see if we make a class for the four different scoring plays, that way we have the EP and EP_bootstrap
    '''
    def __init__(self, name, base_value):
        self.name = name  # This is like "TD" or "ROUGE" or whatever
        self.EP = numpy.empty(3, dtype='Float64')
        self.EP[1] = base_value
        self.EP_bootstrap = None

high_accuracy = True  # This is a quick boolean to drastically reduce the degree of precision of our modeling for testing purposes
if high_accuracy:
    BOOTSTRAP_SIZE = 1000  # Number of bootstrap iterations to use
    forest_trees = 1000
    neural_network = (100, 100, 100)
    KFolds = 10
else:
    BOOTSTRAP_SIZE = 200  # Number of bootstrap iterations to use
    forest_trees = 100
    neural_network = (20, 20, 20)
    KFolds = 3


CONFIDENCE = 0.025  # The one-sided confidence interval size for all statistical tests
THRESHOLD = 100  # The minimum N to include in the graphs
DISTANCE_LIMIT = 51  # This is the max size of P(1D), etc. we're accepting. Usually 26 (meaning 25) but we'll try with longer ones.
alpha_scores = [["FG", False], ["FG", True],
                ["HALF", False],
                ["ROUGE", False], ["ROUGE", True], 
                ["SAFETY", False], ["SAFETY", True], 
                ["TD", False], ["TD", True]]
score_values = {"FG": scoring_play("FG", 3),
                "ROUGE": scoring_play("ROUGE", 2),
                "SAFETY": scoring_play("SAFETY", -2),
                "TD": scoring_play("TD", 7),
                "HALF": scoring_play("HALF", 0)}

gamelist = []  # The gamelist holds all the games

# Holds a default value to avoid errors when comparing to None
DummyArray = numpy.full(BOOTSTRAP_SIZE, -100, dtype='int32')

passerList = []
receiverList = []
tacklerList = []
returnerList = []
rusherList = []
kickerList = []
intercepterList = []

CISTeams = ["SFX", "SMU", "ACA", "MTA", "BIS",
            "SHE", "LAV", "MON", "CON", "MCG",
            "OTT", "CAR", "QUE", "TOR", "YRK", "MAC", "GUE", "WAT", "WLU", "WES", "WIN",
            "MAN", "REG", "SKH", "ALB", "CGY", "UBC", "SFU"]
CISConferences = ["AUS", "RSEQ", "OUA", "CWUAA", "NONCON"]

swaps = [["Daniel Daniel Petermannropped pass","Daniel Petermann"],
["Felix Faubert-Lussierussier","Felix Faubert-Lussier"],
["83-Michel-Pierre Pontbrian","Michel-Pierre Pontbriand"],
["Jahlani Gilbert-Knorrenen","Jahlani Gilbert-Knorren"],
["Ngeleka Muamba, Johnathan","Johnathan Ngeleka Muamba"],
["Simon Gingras-Gagnonagnon","Simon Gingras-Gagnon"],
["Thera-Plamondon, Brandon","Brendon Thera-Plamondon"],
["ADELEYE-APANISI, KELVIN","Kelvin Adeleye-Apanisile"],
["Ellis-McDermid, Krystin","Krystin Ellis-McDermid"],
["Davis-Reynolds, Kasean","Kasean Davis-Reynolds"],
["Gabriel-Cannon, Jordan","Jordan Gabriel-Cannon"],
["Gingrich-Hadley, Dylan","Dylan Gingrich-Hadley"],
["John Ngeleka Muamathan","Johnathan Ngeleka Muamba"],
["Moore-Williams, Jamiel","Jamiel Moore-Williams"],
["Sean Thomas-Erlington.","Sean Thomas-Erlington"],
["Giannikipoulos, Peter","Peter Giannikopoulos"],
["Giannikopoulos, Peter","Peter Giannikopoulos"],
["Abdel-Rahim, Abdraman","Abdraman Abdel-Rahim"],
["Ciraolo-Brown, Jaxon","Jaxon Ciraolo-Brown"],
["Dika-Balotoken, Yann","Yann Dika-Balotoken"],
["Dika-Balotoken, Yann","Yann Dika-Balotoken"],
["Joel Joel Chevrefils","Joel Chevrefils"],
["Kyle van Wynsberghee","Kyle van Wynsberghe"],
["Rose-Standish, Myles","Myles Rose-Standish"],
["Battistella, Domenic","Domenic Battistella"],
["Bouffard, Alexandre","Alexandre Bouffard"],
["D'Hollander, Curtis","Curtis D'Hollander"],
["D'HOLLANDER, CURTIS","Curtis D'Hollander"],
["ï¿½tienneLï¿½garï¿½","Etienne Legare"],
["Justin Chapdelaine.","Justin Chapdelaine"],
["Matthews-Reid, Clay","Clay Matthews-Reid"],
["Roesch-Crane, Dylan","Dylan Roesch-Crane"],
["SARFO-BOATENG, JOJO","JoJo Sarfo-Boateng"],
["Steve Ventrescateve","Steve Ventresca"],
["Tanvir Bhangooanvir","Tanvir Bhangoo"],
["Tarrence Crawfordrd","Tarrence Crawford"],
["GILLANDERS, BRENDAN","Brendan Gillanders"],
["55-Thomas Kuchiran","Thomas Kuchiran"],
["Dika-Balotok, Yann","Yann Dika-Balotoken"],
["Ryan Chmielewskiya","Ryan Chmielewski"],
["Scott Caterinecott","Scott Caterine"],
["Steve Ventrescatev","Steve Ventresca"],
["van Gylswyk, Quinn","Quinn van Gylswyk"],
["Carmichael, Curtis","Curtis Carmichael"],
["Naccarato, Anthony","Anthony Naccarato"],
["Shortill, Nicholas","Nicholas Shortill"],
["2-Gagnier, Maxime","Maxime Gagnier"],
["24-Duane McKenzie","Duane McKenzie"],
["41-Bryan Charleau","Bryan Charleau"],
["44-Mathieu Parent","Mathieu Parent"],
["5-Justin Powlowsk","Justin Powlowski"],
["5-Matthew Leblanc","Matthew Leblanc"],
["6-Sylvester Sarfo","Sylvester Sarfo"],
["66-Etienne Legare","Etienne Legare"],
["82-T Hetherington","Tom Hetherington"],
["91-William Miller","William Miller"],
["Courtney Bishopop","Courtney Bishop"],
["Daniel Petermann.","Daniel Petermann"],
["Dimitroff, Dillon","Dillon Dmitroff"],
["Franï¿½ois Bisson","Francois Bisson"],
["Jason Richardsson","Jason Richardson"],
["Manchulenko, Chad","Chad Manchulenko"],
["Matt BondLapointe","Matthew Bond-Lapointe"],
["Petermann, Daniel","Daniel Petermann"],
["Steve Ventrescaen","Steve Ventresca"],
["Brissette, Tyrese","Tyrese Brissett"],
["Ventresca, Steven","Steven Ventresca"],
["Lucyshyn, Matthew","Matthew Lucyshyn"],
["12-Rylan Colwell","Rylan Colwell"],
["14-Maxime BeRube","Maxime Berube"],
["5-Konrad Wasiela","Konrad Wasiela"],
["Ben Ben O'Connor","Ben O'Connor"],
["Ben O'Connor, M.","Michael O'Connor"],
["DALEKOS, DEMETRI","Demetri Dalekos"],
["Dominique Noï¿½l","Dominique Noel"],
["E Gribbons-Shru ","Ed Gribbons-Shrubsole "],
["Fochestato, Brad","Brad Fochesato"],
["Fred. LAVerville","Frederic Laverville"],
["Izquierdo, Jacob","Jacob Izquierdo"],
["Joe Richardsonos","Joseph Richardson"],
["LAVincent Plante","Vincent Plante"],
["M.-Alex Brunette","Marc-Antoine Brunette"],
["Macdonell, Scott","Scott Macdonell"],
["Math. Guï¿½rette","Mathieu Guerette"],
["Normandin, Keith","Keith Normandin"],
["Peter Carriï¿½re","Peter Carriere"],
["Rodrigues, Marco","Marco Rodrigues"],
["MIREAULT, MAXIME","Maxime Mireault"],
["Smellie, Dashaun","Dashaun Smellie"],
["4-Modibo Sidibe","Modibo Sidibe"],
["55-Eric Maranda","Eric Maranda"],
["6-Vincent Gagne","Vincent Gagne"],
["A Malandruccolo","Anthony Malandruccolo"],
["A. Begin-Drolet","Benjamin Howlett"],
["A. Contreras Fa","Angel Contreras Farias"],
["A. Couturier-L.","Anthony Couturier-Lagace"],
["A. Couturier-La","Anthony Couturier-Lagace"],
["A. Cromer-Emond","Alex Cromer-Emond"],
["A. Fordham-Mill","Austin Fordham-Miller"],
["A. Kyriocopulos","Andrew Kyriakou"],
["A. Malandruccol","Anthony Malandruccolo"],
["A. Ogbongbemiga","Alex Ogbongbemiga"],
["A. Wilson-Agost","Allah Wilson-Agosto"],
["A.Malandruccolo","Anthony Malandruccolo"],
["ALB Abdel-Rahim","Abdraman Abdel-Rahim"],
["Alex F.-LABONTE","Alex Fortier-Labonte"],
["Alex. F-Labonte","Alex Fortier-Labonte"],
["Alex. Fortier-L","Alex Fortier-Labonte"],
["Alex. Gravel-V.","Alexandre Gravel-Vermet"],
["Alex. Hutchison","Alex Hutchinson"],
["Alfr. Dela-Cruz","Alfred Dela-Cruz"],
["Andrew Seinet-S","Andrew Seinet-Spaulding"],
["Anth. Deschamps","Anthony Deschamps"],
["B. Bernier-Laws","Brody Bernier-Lawson"],
["B. VanKoughnett","Braden VanKoughnett"],
["B. von Muehldor","Ben Von Muehldorfer"],
["B. Von Muehldor","Ben Von Muehldorfer"],
["B. Von muehldor","Ben Von Muehldorfer"],
["B. vonMuehldorf","Ben Von Muehldorfer"],
["B. Wishloff-Dob","Bryson Wishloff-Dobush"],
["Ben D'Aguilaren","Ben D'Aguilar"],
["Ben Megarrynett","Bennett Megarry"],
["Blanchard, Josh","Josh Blanchard"],
["BOND-LAPOINT,M.","Matthew Bond-Lapointe"],
["Brend. Carriere","Brenden Carriere"],
["Brend. McKinney","Brenden McKinney"],
["C Riby-Williams","Charles Riby-Williams"],
["C-Evens Peltrop","Charles-Evens Peltrop"],
["C-Wil. Tremblay","Charles-William Tremblay"],
["C. Cardilicchia","Charly Cardilicchia"],
["C. Hutter-Coppi","Christian Hutter-Coppin"],
["C. Laing-Richar","Cam Laing-Richardson"],
["C. Matthews-Rei","Clay Matthews-Reid"],
["C. Sveinbjornso","Ciaran Sveinbjornson"],
["C. Vaillancourt","Cedric Vaillancourt"],
["C.Evens Peltrop","Charles-Evens Peltrop"],
["Ch. Marchand-T.","Charles Marchand-Thibault"],
["Charles-Brow,S.","Shaiheem Charles-Brown"],
["Christop. Mbiya","Christopher Mbiya"],
["D Guzylak-Messa","Dante Guzylak-Messam"],
["D Jupiter-Deane","Daeshaun Jupiter-Deane"],
["D Mastroguisepp","Dante Mastroguiseppe"],
["D. Burgher Jack","Deurell Burgher Jackson"],
["D. Guzylak-Mess","Dante Guzylak-Messam"],
["D. Jupiter-Dean","Daeshaun Jupiter-Deane"],
["D. N'Galamulume","Djuwa N'Galamulume"],
["D. Palmer-Salmo","Daniel Palmer-Salmon"],
["D. Roesch-Crane","Dylan Roesch-Crane"],
["D'Aguilar, Benj","Ben D'Aguilar"],
["Dani. Tshiamala","Daniel Tshiamala"],
["Daniel Palmer-S","Daniel Palmer-Salmon"],
["Daniel Valente.","Daniel Valente"],
["Dika-Balotok,Y.","Yann Dika-Balotoken"],
["Dimitroff, Dill","Dillon Dimitroff"],
["Disch. Thompson","Dischaine Thompson"],
["Dmyt. Povalyaev","Dmytro Povalyaev"],
["Domin. Frappier","Dominic Frappier"],
["E Mrabure-Ajufo","Ese Mrabure-Ajufo"],
["E. Aboagye-Gyan","Emmanuel Aboagye-Gyan"],
["E. Bainomugisha","Enoka Bainomugisha"],
["E. Deschambault","Eric Deschambault"],
["E. Gribbons-Shr","Ed Gribbons-Shrubsole"],
["E. Mrabure-Ajuf","Ese Mrabure-Ajufo"],
["E. Penney-Larye","Enoch Penney-Laryea"],
["F. Tessier-Wadd","Felix Tessier-Waddell"],
["Fernandes, Cory","Cory Fernandes"],
["Fochesato, Brad","Brad Fochesato"],
["FOCHESATO, BRAD","Brad Fochesato"],
["Franc. Bradette","Francis Bradette"],
["G. Kourtesiotis","George Kourtesiotis"],
["Greenwood, Cory","Cory Greenwood"],
["Greg. Alexandre","Gregoire Alexandre"],
["Guil. Desmarais","Guillaume Desmarais"],
["Guill. Laflamme","Guillaume Laflamme"],
["Guill. LevesQUE","Guillaume Levesque"],
["Guill. Levesque","Guillaume Levesque"],
["Guill. Trottier","Guillaume Trottier"],
["Gust. Sylvestre","Gustave Sylvestre"],
["Harris. Maloney","Harrison Maloney"],
["I. Guzylak-Mess","Isaiah Guzylak-Messam"],
["I. GuzylakMessa","Isaiah Guzylak-Messam"],
["Isaiah G-Messam","Isaiah Guzylak-Messam"],
["J Oda-Gallagher","John Oda-Gallagher"],
["J Petit-Frï¿½re","J Petit-Frere"],
["J-Pierre Munroe","Jean-Pierre Munroe"],
["J-Remi Champoux","Jean-Rémi Champoux"],
["J. Battenfelder","Jacob Battenfelder"],
["J. Britton-Bail","Josh Britton-Bailey"],
["J. Ciraolo-Brow","Jaxon Ciraolo-Brown"],
["J. Feoli Gudino","Julian Feoli-Gudino"],
["J. Feoli-Gudino","Julian Feoli-Gudino"],
["J. Fleurissaint","James Fleurissaint"],
["J. Hyland-Benne","Jaiden Hyland-Bennett"],
["J. Le Guehennec","Julien Le Guehennec"],
["J. Magan-France","Jeremy Magan-France"],
["J. McCarthy-Bar","Jamal McCarthy-Barnett"],
["J. Sarfo-Boaten","JoJo Sarfo-Boateng"],
["J. SARFO-BOATEN","JoJo Sarfo-Boateng"],
["J. States-McCle","Jassin States-McClean"],
["J. White-Frayne","Jadin White-Frayne"],
["Jarret St. John","Jarret St John"],
["Jean-C Bouchard","Jean-Christophe Bouchard"],
["Jean-Franc. Cyr","Jean-Francois Cyr"],
["Jean-Ph. Hebert","Jean-Philippe Hebert"],
["Jean-S Guilbert","Jean-Simon Guilbert"],
["Jean-Sam. Blanc","Jean-Samuel Blanc"],
["Jeremy Magan-F.","Jeremy Magan-France"],
["Jeremy Megan-F.","Jeremy Magan-France"],
["Jul. Pontbriand","Julien Pontbriand"],
["K Deutschendorf","Kristopher Deutschendorf"],
["K. Adeleye-Apan","Kelvin Adeleye-Apanisile"],
["K. Cheickh Mbay","Khadim Cheickh Mbay"],
["K. Davis-Reynol","Kasean Davis-Reynolds"],
["K. Flannery-Fle","Kieran Flannery-Fleck"],
["K. Fraser-Audit","Kyle Fraser-Audit"],
["K. Schaffer-Bak","Kian Schaffer-Baker"],
["K. Vaillancourt","Kris Vaillancourt"],
["Kam. Katchelewa","Kamba Katchelewa"],
["Klukas, Michael","Michael Klukas"],
["Kon. Burtenshaw","Konner Burtenshaw"],
["Koronkiewicz,T.","Tristian Koronkiewicz"],
["Kowalewsky,Just","Justus Kowalewsky"],
["Kyle Fraser-Aud","Kyle Fraser-Audit"],
["L Stavropoulous","Loukas Stavropoulos"],
["L-F Dessureault","Louis-Frederic Dessurault"],
["L. Brouilllette","Louis Brouillette"],
["L. Burton-Krahn","Luke Burton-Krahn"],
["L. Guimont-Mota","Luis Guimont-Mota"],
["L. Spencer-Enri","Liam Spencer-Enright"],
["L. Stavropoulos","Loukas Stavropoulos"],
["L.F Dessureault","Louis-Frederic Dessurault"],
["L.F. Dessurault","Louis-Frederic Dessurault"],
["Louis-C. Moisan","Louis-Charles Moisan"],
["Louis-Ch Moisan","Louis-Charles Moisan"],
["LSpencerEnright","Liam Spencer-Enright"],
["M LAPOINTE-BOND","Matthew Lapointe-Bond"],
["M. BondLapointe","Matthew Bond-Lapointe"],
["M. BONDLAPOINTE","Matthew Bond-Lapointe"],
["Magan-France,J.","Jeremy Magan-France"],
["Marc-Oliv. East","Marc-Olivier East"],
["Mikael P-Ayotte","Mikael Piche-Ayotte"],
["Mikael Piche-A.","Mikael Piche-Ayotte"],
["N. Fraser-Green","Nicholas Fraser-Greene"],
["N.Fraser-Greene","Nicholas Fraser-Greene"],
["Nathan Doyon-S.","Nathaniel Doyon-Simon"],
["Nic. Gaudreault","Nicholas Gaudreault"],
["Nick Shorthillo","Nicholas Shortill"],
["O Cain-Tremblay","Olivier Cain-Tremblay"],
["O'Donnell, Matt","Matthew O’Donnell"],
["P Giannikopolou","Peter Giannikopoulos"],
["P-O. Grenier-G.","Pier-Olivier Grenier-Gachet"],
["P-Yves Lavergne","Pier-Yves Lavergne"],
["P. Lach-Edwards","Paolo Lach-Edwards"],
["Ph. Archambault","Philippe Archambault"],
["Phil Bruneau-P.","Philippe Bruneau-Pichet"],
["Pierre-L. Labb?","Pierre-Luc Labbe"],
["Pierre-L. Labbe","Pierre-Luc Labbe"],
["Pierre-N. Konan","Pierre-Nicolas Konan"],
["Pierre-O Daloze","Pierre-Olivier Daloze"],
["Q. Van De Cruiz","Quincey Van De Cruize"],
["Quent. Bienaime","Quentin Bienaime"],
["R. Ravensbergen","Robert Ravensbergen"],
["Raf. Bouffard-P","Rafaël Bouffard-Proulx"],
["Roesch Crane, D","Dylan Roesch-Crane"],
["Roesch-Crane,Dy","Dylan Roesch-Crane"],
["Ryan Chmielewsk","Ryan Chmielewski"],
["S. Davis-Ramloc","Shaquille Davis-Ramlochan"],
["S. Ishimwe-Bag.","Stephane Ishimwe-Baganizi"],
["S. Ishimwe-Baga","Stephane Ishimwe-Baganizi"],
["Samuel Piche-L.","Samuel Piche-Luneau"],
["Schuyl. O'Brien","Schuyler O'Brien"],
["T Lewis-Gostlin","Tamaul Lewis-Gostlin"],
["T. Buama-Mafuta","Tresor Buama-Mafuta"],
["T. Dixon-Bowden","Tyrique Dixon-Bowden"],
["T. Koronkiewicz","Tristian Koronkiewicz"],
["T. Lewis-Gostli","Tamaul Lewis-Gostlin"],
["Thierry Nkury-M","Thierry Nkury-Muryango"],
["TJ Chase Dunawa","TJ Chase-Dunawa"],
["Tommy Roadley-T","Tommy Roadley-Trohatos"],
["Trist F-Casault","Tristan Fiske-Casault"],
["Tristan Fiske-C","Tristan Fiske-Casault"],
["Valent. Gnahoua","Valentin Gnahoua"],
["Will Tremblay-H","William Tremblay-Harnois"],
["Y Dike-Baltoken","Yann Dika-Balotoken"],
["Y. Angelopoulos","Yanni Angelopoulos"],
["Y. Dika-Balotok","Yann Dika-Balotoken"],
["Y. Langelier-V.","Yannick Langelier-Vanasse"],
["Yan Langelier-L","Yannick Langelier-Vanasse"],
["Yan Langelier-V","Yannick Langelier-Vanasse"],
["Yann. L-Vanasse","Yannick Langelier-Vanasse"],
["Z van Kerrebroe","Zach Van Kerrebroeck"],
["Z. Van Kerrebro","Zach Van Kerrebroeck"],
["Zachary BaderSh","Zachary Bader-Shamai"],
["Amankwaa, Perry","Perry Amankwaa"],
["Callahan, Caleb","Caleb Callahan"],
["Karamath, Aaron","Aaron Karamath"],
["Pezzetta, Chris","Chris Pezzetta"],
["Gladman, Carter","Carter Gladman"],
["NGANDUI, FRANCK","Franck Ngandui"],
["Poirier, Jordan","Jordan Poirier"],
["33-S. Tillotson","Sheldon Tillotson"],
["19-Warren Kean","Warren Kean"],
["24-C Mccrystal","Charlie McCrystal"],
["7-Butler, Cody","Cody Butler"],
["A Begin-Drolet","Andre Begin-Drolet"],
["A Buteau-Protz","Anton Buteau-Protz"],
["A Laberge-Chun","Alex Laberge-Chung"],
["A Stora-Nelson","Aaron Stora-Nelson"],
["A. Barrenechea","Agustin Barrenechea"],
["A. Bonaventura","Andrea Bonaventura"],
["A. Fitzpatrick","Alex Fitzpatrick"],
["A. Lefebvre-T.","Alexandre Lefebvre-Tardif"],
["A. Plante-Ajah","Anthony Plante-Ajah"],
["A. S-Spaulding","Andrew Seinet-Spaulding"],
["A.Begin-Drolet","Andre Begin-Drolet"],
["Adewale, Bamki","Bamki Adewale"],
["Alex. L-Tardif","Alexandre Lefebvre-Tardif"],
["Anth. Temelini","Anthony Temelini"],
["Anth. Vendrame","Anthony Vendrame"],
["Aprile, Johnny","Johnny Aprile"],
["B Bernier-Laws","Brody Bernier-Lawson"],
["B De Palezieux","Braeden De Palezieux"],
["B von Muehldor","Ben Von Muehldorfer"],
["B Wishloff-Dob","Bryson Wishloff-Dobush"],
["Baldassi, Nick","Nick Baldassi"],
["Belanger, Joey","Joey Belanger"],
["Benj. Bergeron","Benjamin Bergeron"],
["Braccio, Frank","Frank Braccio"],
["C Cardilicchia","Charly Cardilicchia"],
["C Hinschberger","Craig Hinschberger"],
["C Laing-Richar","Cam Laing-Richardson"],
["C. Irwin-Lewis","Connor Irwin-Lewis"],
["C. Lussier-Roy","Cedric Lussier-Roy"],
["C. Manchulenko","Chad Manchulenko"],
["C. Riby-Wilson","Charles Riby-Williams"],
["C.-W. Tremblay","Charles-William Tremblay"],
["C.Cardilicchia","Charly Cardilicchia"],
["Ced. Ferdinand","Cedric Ferdinand"],
["Ch. Marchand-T","Charles Marchand-Thibault"],
["Con. McQuilkin","Connor McQuilkin"],
["D Dumas-Goulet","David Dumas-Goulet"],
["D Guzylak-Mess","Dante Guzylak-Messam"],
["D Massey-Hirth","Damian Massey-Hirt"],
["D Palmer-Salmo","Daniel Palmer-Salmon"],
["D Roesch-Crane","Dylan Roesch-Crane"],
["D. Kouka-Ganga","Dominique Kouka-Ganga"],
["D. KOUKA-GANGA","Dominique Kouka-Ganga"],
["D. Massey-Hirt","Damian Massey-Hirt"],
["D. Ngalamulume","Daniel Ngalamulume"],
["D. Steenbergen","Dylan Steenbergen"],
["Dan. Tshiamala","Daniel Tshiamala"],
["Dasiuk, Justin","Justin Dasiuk"],
["Demi A.-Olusae","Demi Adeleye-Olusae"],
["Dj. Buissereth","DJ Buissereth"],
["E Deschambault","Eric Deschambault"],
["E Mrabure Ajuf","Ese Mrabure-Ajufo"],
["E. De la Garza","Eddie De la Garza"],
["Eeuwes, Robert","Robert Eeuwes"],
["Emm. Theriault","Emmanuel Theriault"],
["eric Bellemare","Eric Bellemare"],
["Eric CHIBULUZO","Eric Chibuluzo"],
["G Kourtesiotis","George Kourtesiotis"],
["Graveson, Zach","Zach Graveson"],
["Guill. Boucher","Guillaume Boucher"],
["Guill. Paradis","Guillaume Paradis"],
["Guill. Senecal","Guillaume Senecal"],
["Heslop, Daniel","Daniel Heslop"],
["I GuzylakMessa","Isaiah Guzylak-Messam"],
["J Battenfelder","Jacob Battenfelder"],
["J Britton-Bail","Josh Britton-Bailey"],
["J Ciraolo-Brow","Jaxon Ciraolo-Brown"],
["J Cowperthwait","Jason Cowperthwaite"],
["J Hetherington","Jordan Hetherington"],
["J Hyland-Benne","Jaiden Hyland-Bennett"],
["J Jones-Carter","Julius Jones-Carter"],
["J Magan-France","Jeremy Magan-France"],
["J White-Frayne","Jadin White-Frayne"],
["J?r?me D?ry-L.","Jerome Dery-L"],
["J. Braithwaite","Jason Braithwaite"],
["J. DesLauriers","JJ DesLauriers"],
["J. Petit-Fr?re","J. Petit-Frere"],
["J. Socholotiuk","Jordan Socholotiuk"],
["J. Surdykowski","Jake Surdykowski"],
["J. WILSON-ROSS","Jordan Wilson-Ross"],
["Jacob Gagne-L.","Jacob Gagne-Lanthier"],
["Jean-Ph. Begin","Jean-Philippe Begin"],
["Jean-Ph. Hudon","Jean-Philippe Hudon"],
["Jeff St. Louis","Jeffrey St Louis"],
["Jer. Verreault","Jeremie Verreault"],
["Jonat. Woodley","Jonathan Woodley"],
["Jorda Cobourne","Jordan Cobourne"],
["Jos. Archibald","Joshua Archibald"],
["Jos. Fulginiti","Joseph Fulginiti"],
["K Cheickh Mbay","Khadim Cheickh Mbay"],
["K Davis-Reynol","Kasean Davis-Reynolds"],
["K Schaffer-Bak","Kian Schaffer-Baker"],
["K Vaillancourt","Kris Vaillancourt"],
["K. Ghazi Zadeh","Kiarash Ghazi Zadeh"],
["K. Kuma-Mintah","Kofi Kuma-Mintah"],
["Krausnick-Groh","Alex Krausnick-Groh"],
["L Brouilllette","Louis Brouillette"],
["L Guimont-Mota","Luis Guimont-Mota"],
["L Stavropoulos","Loukas Stavropoulos"],
["L. Brouillette","Louis Brouillette"],
["L. GuiMON-Mota","Luis Guimont-Mota"],
["L. Hakunavanhu","Luther Hakunavanhu"],
["L. Haqunavinhu","Luther Hakunavanhu"],
["L. Moussenguet","Louve Moussenguet"],
["LeMARQUAND, S.","Simon Le Marquand"],
["Luke VanRuyven","Luke van Ruyven"],
["M BOND-LAPOINT","Matthew Bond-Lapointe"],
["M BONDLAPOINTE","Matthew Bond-Lapointe"],
["M Piche-Ayotte","Mikael Piche-Ayotte"],
["M. Besseghieur","Malik Besseghieur"],
["M. Chamberlain","Matt Chamberlain"],
["M. Halbgewachs","Matthew Halbgewachs"],
["Mak Stephenson","Mark Stephenson"],
["Manchulenko,C.","Chad Manchulenko"],
["MARQUAND,S. LE","Simon Le Marquand"],
["Math. Guerette","Mathieu Guérette"],
["Matth Rossetti","Matthew Rossetti"],
["Matthe Peressi","Matthew Peressi"],
["Mich. Donnelly","Michael Donnelly"],
["Moortgat, Kyle","Kyle Moortgat"],
["Morrison, Alex","Alex Morrison"],
["Moussenguet,L.","Louve Moussenguet"],
["N Fraser-Green","Nicholas Fraser-Greene"],
["N. Applewhaite","Nigel Applewhaite"],
["N. Baillargeon","Nicolas Baillargeon"],
["N. Cartagenise","Nicholas Cartagenise"],
["N. Christopher","Nathan Christopher"],
["Nathan. Berlus","Nathaniel Berlus"],
["Nic. Champagne","Nicolas Champagne"],
["Ol. C-Tremblay","Olivier Cain-Tremblay"],
["P DOUANGCHANTH","Patrick Douangchantha"],
["P Lach-Edwards","Paolo Lach-Edwards"],
["P-J. Schrembre","Phillip-Joseph Schembre"],
["Phil. Lapierre","Philippe Lapierre"],
["Pierre-L.Labbe","Pierre-Luc Labbe"],
["Plumpton, Greg","Greg Plumpton"],
["Q Van De Cruiz","Quincey Van De Cruize"],
["Q. VanDeCruize","Quincey Van De Cruize"],
["R. McClinnahan","Rae'Qwan McClinnahan"],
["Ramez Popal-H.","Ramez Popal-Hamidi"],
["Roesch-Crane,D","Dylan Roesch-Crane"],
["Ryth-J. Giraud","Ryth-Jean Giraud"],
["S Murdock-Reid","Shomari Murdock-Reid"],
["S. Kofi-Akuffo","Stephen Kofi-Akuffo"],
["S. LaMONagne 0","Simon Lamontagne"],
["S. Le Marquand","Simon Le Marquand"],
["S. LE MARQUAND","Simon Le Marquand"],
["S. Martimbault","Sebastien Martimbault"],
["Samaï¿½l LAVud","Samael Lavaud"],
["Samaï¿½L LAVud","Samael Lavaud"],
["Simeon ROTTier","Simeon Rottier"],
["Simon Aubin-L.","Simon Aubin-Lavoie"],
["Sinclair, Adam","Adam Sinclair"],
["Steph.Trivieri","Stephen Trivieri"],
["T Dixon-Bowden","Tyrique Dixon-Bowden"],
["T Van schyndel","Timothy van Schyndel"],
["T Van Schyndel","Timothy van Schyndel"],
["T. Cadwallader","Tanner Cadwallader"],
["T. Cooke-Brown","Taylor Cooke-Brown"],
["T. Goldsworthy","Tyler Goldsworthy"],
["T. KIRKPATRICK","Thomas Kirkpatrick"],
["Trentham, Troy","Troy Trentham"],
["Wilf. Munoz M.","Shaquille Munroe"],
["Wisdom, Marcus","Marcus Wisdom"],
["Xav. Angers-G.","Xavier Angers-Gauthier"],
["Y Dika Balotok","Yann Dika-Balotoken"],
["Y Dika-Balotok","Yann Dika-Balotoken"],
["Y Langelier-V.","Yannick Langelier-Vanasse"],
["Y Langelier-Va","Yannick Langelier-Vanasse"],
["Y. D-Balotoken","Yann Dika-Balotoken"],
["Z Van Kerrebro","Zach Van Kerrebroeck"],
["Z. Hirshmiller","Zach Hirshmiller"],
["Bratton, Cavin","Cavin Bratton"],
["Mathieu, Ethan","Ethan Mathieu"],
["Dan Petermann","Daniel Petermann"],
["1-Sammy Okpro","Sammy Okpro"],
["31-Namdi Metu","Namdi Metu"],
["8-Jason Milne","Jason Milne"],
["9-Pat Donovan","Pat Donovan"],
["95-Roody Jean","Roody Jean"],
["A Barrenechea","Agustin Barrenechea"],
["A Bonaventura","Andrea Bonaventura"],
["A Plante-Ajah","Anthony Plante-Ajah"],
["A. Boudreault","Andre Boudreault"],
["A. F -Labonte","Alex Fortier-Labonte"],
["A. Giovanetto","Terry Giovannetti"],
["A. Mielczarek","Aiden Mielczarek"],
["A. Panchyshyn","Aiden Panchyshyn"],
["A. Panschysyn","Aiden Panchyshyn"],
["A. Tchobanian","Ara Tchobanian"],
["A.Barrenechea","Agustin Barrenechea"],
["A.Bonaventura","Andrea Bonaventura"],
["ALBel Boucher","Abel Boucher"],
["B Fitzpatrick","Bryson Fitzpatrick"],
["B. Borthistle","Brent Borthistle"],
["B. Gillanders","Brendan Gillanders"],
["B. GILLANDERS","Brendan Gillanders"],
["Benj. Nolette","Benjamin Nolette"],
["Bockru, Macho","Macho Bockru"],
["C Manchulenko","Chad Manchulenko"],
["C Riby-Wilson","Charles Riby-Williams"],
["C Vlowianitis","Chris Vlowianitis"],
["C-David Erius","Carl-David Erius"],
["C. Bujold-Abu","Cordell Bujold-Abu"],
["C. Carmichael","Curtis Carmichael"],
["C. Williamson","Callum Williamson"],
["C. Woodmansey","Curtis Woodmansey"],
["Carl-D. Erius","Carl-David Erius"],
["CARMICHEAL,K.","Keven Carmicheal"],
["Clarke,Justin","Justin Clarke"],
["CORNELL, Mike","Michael Cornell"],
["D Chapdelaine","Dylan Chapdelaine"],
["D Massey-Hirt","Damian Massey-Hirt"],
["D. Bellardini","Dominic Bellardini"],
["D. Gavrilovic","Djordje Gavrilovic"],
["D. Hinsperger","Devon Hinsperger"],
["D. Mandalfino","Dom Mandalfino"],
["D. Nethersole","David Nethersole"],
["D. Neustaeter","Dwayne Neustaeter"],
["D. Obiang Jr.","Daniel Obiang Jr"],
["D. Thibaudeau","Darcy Thibaudeau"],
["D. Zimmermann","Dillon Zimmermann"],
["Damian M-Hirt","Damian Massey-Hirt"],
["Davidson, Ben","Ben Davidson"],
["Dylan SHEvill","Dylan Shervill"],
["Dylan SHEynes","Dylan Hynes"],
["E G-Shrubsole","Ed Gribbons-Shrubsole"],
["E Lyons-Keely","Evinn Lyons-Keely"],
["E. Kurbegovic","Edis Kurbegovic"],
["E. Millington","Ezra Millington"],
["E. Sokolowski","Eddie Sokolowski"],
["Erasmo, Jayde","Jayde Erasmo"],
["F. Daigneault","Felix Daigneault"],
["G. Bezrunchko","Geoff Bezruchko"],
["G. Jean-Louis","George Jean-Louis"],
["Ga. McDonnell","Garrin McDonnell"],
["Gelevan, Doug","Doug Gelevan"],
["Guill. Beland","Guillaume Beland"],
["Guill. Doucet","Guillaume Doucet"],
["Guill. Girard","Guillaume Girard"],
["Guill. PaQUEt","Guillaume Paquet"],
["Guill. Paquet","Guillaume Paquet"],
["Guill. Robert","Guillaume Robert"],
["Guill.Boucher","Guillaume Boucher"],
["H. De la rosa","Hector De La Rosa"],
["H. De La Rosa","Hector De La Rosa"],
["J Braithwaite","Jason Braithwaite"],
["J DesLauriers","JJ DesLauriers"],
["J Manchulenko","Chad Manchulenko"],
["J PETIT-FRERE","Jean Petit-Frere"],
["J Petit-Frere","Jean Petit-Frere"],
["J Protonentis","James Protonentis"],
["J WILSON-ROSS","Jordan Wilson-Ross"],
["J Wotherspoon","John Wotherspoon"],
["J. Baronaitis","Justin Baronaitis"],
["J. Cunningham","Jimmie Cunningham"],
["J. DaSilveira","Jainyme DaSilveira"],
["J. Dasilveira","Jainyme DaSilveira"],
["J. Filippelli","Jordan Filippelli"],
["J. Ghazizadeh","Jacob Ghazizadeh"],
["J. Kapelanski","Jeremy Kapelanski-Lamoureux"],
["J. Laboccetta","Jacob Laboccetta"],
["J. McNaughton","James McNaughton"],
["J. McNAUGHTON","James McNaughton"],
["J. Simmerling","Julian Simmerling"],
["J. Washington","Jaeden Washington"],
["J. Zlatinszky","Jonah Zlatinszky"],
["J.P. Paquette","Jean-Philippe Paquette"],
["Jacob Gagne-L","Jacob Gagne-Lanthier"],
["JanSHE Hundal","Jansher Hundal"],
["Jean-Ph. Huot","Jean-Philippe Huot"],
["K D.-Reynolds","Kasean Davis-Reynolds"],
["K Kuma-Mintah","Kofi Kuma-Mintah"],
["K. Burtenshaw","Konner Burtenshaw"],
["K. CARMICHEAL","Keven Carmicheal"],
["K. Carruthers","Keegan Carruthers"],
["K.J. HILLAIRE","KJ Hillaire"],
["L Brouillette","Louis Brouillette"],
["L GuiMON-Mota","Luis Guimont-Mota"],
["L. Cunningham","Lukash Cunningham"],
["L. Morassutti","Lawson Morassutti"],
["L. Morissette","Louis Morissette"],
["Lawrence, Ian","Ian Lawrence"],
["M. Hanselwood","Mitchel Henselwood"],
["M. Henselwood","Mitchel Henselwood"],
["M. Metulynsky","Mark Metulynsky"],
["M. STEPHENSON","Mark Stephenson"],
["M. Stephenson","Mark Stephenson"],
["M. Villamizar","Mario Villamizar"],
["Marc-Ol. East","Marc-Olivier East"],
["Martin, Scott","Scott Martin"],
["Mat Ouellet D","Matthew Ouellet De Carlo"],
["N Applewhaite","Nigel Applewhaite"],
["N Baillargeon","Nicolas Baillargeon"],
["N Cartagenise","Nicholas Cartagenise"],
["N. Starchenko","Nikita Starchenko"],
["Nic. Gauthier","Nicolas Gauthier"],
["Oli. Therrien","Olivier Therrien"],
["P Giannikopol","Peter Giannikopoulos"],
["P-A. D'Astous","Pierre-Antoine D'Astous"],
["P.L.Pomerleau","Pierre-Luc Pomerleau"],
["P.Y. Lavergne","Pier-Yves Lavergne"],
["Patrick MEARS","Patrick Mears"],
["Phil. Carrier","Philippe Carrier"],
["Phil. Delorme","Philippe Delorme"],
["Potonentis, J","James Protonentis"],
["Q VanDeCruize","Quincey Van De Cruize"],
["R McClinnahan","Rae'Qwan McClinnahan"],
["R. Montemurro","Roberto Montemurro"],
["R. Northfield","Ryan Northfield"],
["R. Richardson","Ryan Richardson"],
["Richard Lubin","Ricardo Lubin"],
["Rob.Rodrigues","Robbie Rodrigues"],
["S Le Marquand","Simon Le Marquand"],
["S LE MARQUAND","Simon Le Marquand"],
["S. Cezon-Holm","Shaquille Cezont-Holmes"],
["S. Desrochers","Shane Desrochers"],
["Sabourin, Sam","Sam Sabourin"],
["Sam L.-Robert","Samuel Leblanc-Robert"],
["SAM ST-VILLON","Sam St-Villon"],
["Savoie, James","James Savoie"],
["Sh Char-Brown","Shaiheem Charles-Brown"],
["Shaq. Johnson","Shaquille Johnson"],
["T Cooke brown","Taylor Cooke-Brown"],
["T Cooke Brown","Taylor Cooke-Brown"],
["T. McStravick","Tyler McStravick"],
["T. Middlemost","Tyson Middlemost"],
["T. Potopilnyj","Taras Potopilnyj"],
["T. St. Pierre","Tyrone St Pierre"],
["Th. Trepanier","Thomas Trepanier"],
["Y Langelier-V","Yannick Langelier-Vanasse"],
["Yan L-Vanasse","Yannick Langelier-Vanasse"],
["Z Jones-Hurst","Zachary Jones-Hurst"],
["Alfonso, Mike","Mike Alfonso"],
["Basilis, Alex","Alex Basilis"],
["BORNAIS, ALEX","Alex Bornais"],
["Carroll, Alex","Alex Carroll"],
["Durigon, Mark","Mark Durigon"],
["Gardner, Jedd","Jedd Gardner"],
["Groshak, Alex","Alex Groshak"],
["KNIGHTS, CODY","Cody Knights"],
["Kristof, Todd","Todd Kristoff"],
["Raymond, Hugo","Hugo Raymond"],
["Sheahan, Kyle","Kyle Sheahan"],
["SPELLER, CODY","Cody Speller"],
["Archer, Rohan","Rohan Archer"],
["Draper, Blake","Blake Draper"],
["Hannon, Peter","Peter Hannon"],
["Isakov, Boris","Boris Isakov"],
["Joseph, Devin","Devin Joseph"],
["JOSEPH, DEVIN","Devin Joseph"],
["Ledwos, Tyler","Tyler Ledwos"],
["Reason, Blake","Blake Reason"],
["Simard, Kevin","Kevin Simard"],
["J-P. PaQUEtte","Jean-Philippe Paquette"],
["6-S. O'Brien","Sean O'Brien"],
["A F -Labonte","Alex Fortier-Labonte"],
["A Mandalfino","Anthony Mandalfino"],
["A Panchyshyn","Aiden Panchyshyn"],
["A Thibaudeau","Andrew Thibaudeau"],
["A. Chavannes","Azaria Chavannes"],
["A. F-Labonte","Alex Fortier-Labonte"],
["A. Feshanets","Alex Feshanets"],
["A. Grant Jr.","Adrien Grant Jr"],
["A. Grant jr.","Adrien Grant Jr"],
["A. McWhinnie","Andrew McWhinnie"],
["Aaron Clarke","Aaron Clarke"],
["Alek. Papich","Aleksander Papich"],
["Alex. Girard","Alexandre Girard"],
["Alex. Lortie","Alexandre Lortie"],
["B Borthistle","Brent Borthistle"],
["B D'Aguillar","Ben D'Aguilar"],
["B Gillanders","Brendan Gillanders"],
["B GILLANDERS","Brendan Gillanders"],
["B MacFarlane","Brett MacFarlane"],
["B. Collinson","Blake Collinson"],
["B. Deschamps","Brandon Deschamps"],
["B. McCracken","Brendan McCracken"],
["B. Sise-Odaa","Bashiru Sise-Odaa"],
["C Bellerdine","Cory Bellerdine"],
["C Bujold-Abu","Cordell Bujold-Abu"],
["C Carmichael","Curtis Carmichael"],
["C Challenger","Corlan Challenger"],
["C GOODfellow","Cole Goodfellow"],
["C. Armstrong","Corey Armstrong"],
["C. Bergersen","Connor Bergersen"],
["C. Ferdinand","Cory Fernandes"],
["C. Gascoigne","Connor Gascoigne"],
["C. Griffiths","Connor Griffiths"],
["C. Gudziunas","Connor Gudziunas"],
["C. Guglielmi","Carlos Guglielmi"],
["C. Hitchhock","Connor Hitchcock"],
["C. Ihekwoaba","Chima Ihekwoaba"],
["C. Labrecque","Carson Labrecque"],
["C. McCrystal","Charlie McCrystal"],
["C. McQuilkin","Connor McQuilkin"],
["C. Oberegger","Christian Oberegger"],
["C. Patterson","Carter Patterson"],
["C. Schneider","Catlin Schneider"],
["C. Theriault","Cedric Theriault"],
["Cameron, Max","Max Cameron"],
["Ch-E Peltrop","Charles-Evens Peltrop"],
["Ch. Belanger","Charles Belanger"],
["D Bellardini","Dominic Bellardini"],
["D Gavrilovic","Djordje Gavrilovic"],
["D Mandalfino","Dom Mandalfino"],
["D McCutcheon","Daniel McCutcheon"],
["D Neustaeter","Dwayne Neustaeter"],
["D Serravalle","Daniel Serravalle"],
["D. Ainsworth","Dylan Ainsworth"],
["D. Bourdages","Dawlson Bourdages"],
["D. Monestier","Damien Monestier"],
["D. Patterson","Dylan Patterson"],
["D. Termansen","Dominique Termansen"],
["D.Mandalfino","Dom Mandalfino"],
["Deji OdWESle","Deji Oduwole"],
["E Millington","Ezra Millington"],
["E Sokolowski","Eddie Sokolowski"],
["E. Chibuluzo","Eric Chibuluzo"],
["E. Shrubsole","Ed Gribbons-Shrubsole"],
["E.Kurbegovic","Edis Kurbegovic"],
["G Jean-Louis","George Jean-Louis"],
["G. Boscariol","Giovanni Boscariol"],
["Griffiths,C.","Connor Griffiths"],
["H. Gallacher","Hayden Gallacher"],
["J Baronaitis","Justin Baronaitis"],
["J Cunningham","Jimmie Cunningham"],
["J Fitzgerald","John Fitzgerald"],
["J Pendergast","Jeremy Pendergast"],
["J Piotrowski","Jake Piotrowski"],
["J Saddlemyre","Justin Saddlemyre"],
["J Simmerling","Julian Simmerling"],
["J Washington","Jaeden Washington"],
["J. Andrushko","Justin Andrushko"],
["J. Armstrong","Joshua Armstrong"],
["J. Carpenter","Justin Carpenter"],
["J. Croasdale","Justis Croasdale"],
["J. Hipperson","Jerimy Hipperson"],
["J. Keirstead","Jonathan Keirstead"],
["J. Nicoletti","Jake Nicoletti"],
["J. Salfarlie","Jothan Salfarlie"],
["J. Sidsworth","Jordan Sidsworth"],
["J. SMUecSMUt","Jeff Hecht"],
["J. St. James","Jesse St James"],
["J. Sutcliffe","Jordan Sutcliffe"],
["J.P. Primeau","John-Paul Primeau"],
["K Burtenshaw","Konner Burtenshaw"],
["K. Armstrong","Kobe Armstrong"],
["K. McCartney","Karl McCartney"],
["K.Carruthers","Keegan Carruthers"],
["L Morassutti","Lawson Morassutti"],
["L. Fuendling","Luke Fuendling"],
["M Kanopolous","Michael Kanopoulos"],
["M Kanopoulos","Michael Kanopoulos"],
["M Metulynsky","Mark Metulynsky"],
["M Nazartchyk","Maksym Nazartchyk"],
["M STEPHENSON","Mark Stephenson"],
["M Strohmeier","Max Strohmeier"],
["M. BroWATers","Michael Brouwers"],
["M. Chartrand","Mathieu Chartrand"],
["M. Colangelo","Martin Colangelo"],
["M. Esokpunwu","Marshall Esokpunwu"],
["M. Grandison","Marcus Grandison"],
["M. MacMillan","Matt McMillan"],
["M. McEachern","Matt McEachern"],
["M. MCEACHERN","Matt McEachern"],
["M.-A. Laurin","Marc-Antoine Laurin"],
["Mat Guerette","Mathieu Guerette"],
["Matt Renaude","Matthew Renaud"],
["McNair,Jesse","Jesse McNair"],
["Megarry, Ben","Ben Megarry"],
["MOORE, JAMES","James Moore"],
["N Leonidakis","Nick Leonidakis"],
["N Starchenko","Nikita Starchenko"],
["N. Mirijello","Nicholas Mirijello"],
["N. Romanchuk","Nicholas Romanchuk"],
["N. Topolovec","Nik Topolovec"],
["N. Zavarella","Nathan Zavarella"],
["N. ZAVARELLA","Nathan Zavarella"],
["O.J. Sabageh","OJ Sabageh"],
["O.j. Sabageh","OJ Sabageh"],
["P Hutchinson","Paul Hutchinson"],
["P. Ruvalcaba","Patrick Ruvalcaba"],
["Pankewich, F","Frank Pankewich"],
["Pelletier,T.","Travis Pelletier"],
["R Richardson","Ryan Richardson"],
["R. Rodrigues","Robbie Rodrigues"],
["ROZEBOOM, T.","Tucker Rozeboom"],
["S Bartolacci","Stefano Bartolacci"],
["S Desrochers","Shane Desrochers"],
["S LeMarquand","Simon Le Marquand"],
["S Oleksewycz","Sean Oleksewycz"],
["S R-Burbidge","Simon Ryder-Burbidge"],
["S. LaMONagne","Simon Lamontagne"],
["S. Tillotson","Sheldon Tillotson"],
["S. Van Hende","Scott Van Hende"],
["S. Zakrewski","Steve Zakrzewski"],
["Sama?L LAVud","Samael Lavaud"],
["Sama?l LAVud","Samael Lavaud"],
["Sise-Odaa,B.","Bashiru Sise-Odaa"],
["T Greenslade","Tom Greenslade"],
["T Middlemost","Tyson Middlemost"],
["T Potopilnyj","Taras Potopilnyj"],
["T SMUercules","Tristan Hercules"],
["T. Bresciani","Thomas Bresciani"],
["T. Bromfield","Tyrone Bromfield"],
["T. Calverley","Taylor Calverley"],
["T. Chakwesha","Tanaka Chakwesha"],
["T. Creighton","Taylor Creighton"],
["T. Mcgarrity","Trevor McGarrity"],
["T. McGarrity","Trevor McGarrity"],
["T. Pastusiak","Taylor Pastusiak"],
["TTJ Williams","TJ Williams"],
["V. Frangione","Vincenzo Frangione"],
["W Van Ruyven","William Van Ruyven"],
["W Van ruyven","William Van Ruyven"],
["Benson, Zack","Zack Benson"],
["Butler, Cody","Cody Butler"],
["Kealey, Zack","Zack Kealey"],
["Mackie, Mark","Mark Mackie"],
["Nelson, Cass","Cass Nelson"],
["Roberts, Ben","Ben Roberts"],
["P-G Medjeber","Pierre-Giovani Medjeber"],
["S Cezon-Holm","Shaquille Cezont-Holmes"],
["5-Mark Kang","Mark Kang"],
["A Darcovich","Andrew Darcovich"],
["A F-Labonte","Alex Fortier-Labonte"],
["A McWhinnie","Andrew McWhinnie"],
["A Nikouline","Anton Nikouline"],
["A Rochester","Ashton Rochester"],
["A. Dietrich","Andrew Dietrich"],
["A. Federico","Anthony Federico"],
["A. Iwanegbe","Andreas Iwanegbe"],
["A. Petrucci","Anthony Petrucci"],
["A. Pugliese","Antonino Pugliese"],
["A.K. Ismail","AK Ismail"],
["Alex. Turpe","Alexandre Turpe"],
["B McCracken","Brendan McCracken"],
["B Sise-Odaa","Bashiru Sise-Odaa"],
["B Springett","Brett Springett"],
["B. Hamilton","Brett Hamilton"],
["B. Kolybaba","Brandt Kolybaba"],
["B. Kootstra","Bobby Kootstra"],
["B. Lawrence","Blake Lawrence"],
["B. Rockhill","Brandon Rockhill"],
["B. Vanneste","Brandon Vanneste"],
["Bennett, J.","Jake Bennett"],
["BIS, Junior","Junior Bishop"],
["Boucher, G.","Gabriel Boucher"],
["C Armstrong","Corey Armstrong"],
["C Bergersen","Connor Bergersen"],
["C Bilawchuk","Carter Bilawchuk"],
["C Collerile","Christiaan Collarile"],
["C Fernandes","Cory Fernandes"],
["C Gascoigne","Connor Gascoigne"],
["C Hitchcock","Connor Hitchcock"],
["C Ioannides","Christopher Ioannides"],
["C McCrystal","Charlie McCrystal"],
["C Oberegger","Christian Oberegger"],
["C Schneider","Catlin Schneider"],
["C. H-Coppin","Christian Hutter-Coppin"],
["C. Hastings","Cordell Hastings"],
["C. Ringland","Charlie Ringland"],
["Carter, Ben","Ben Carter"],
["D Ainsworth","Dylan Ainsworth"],
["D Himmelman","Detlev Himmelman"],
["D Kucheravy","Dylan Kucheravy"],
["D Monestier","Damien Monestier"],
["D Sprukulis","Danny Sprukulis"],
["D Termansen","Dominique Termansen"],
["D Tshiamala","Daniel Tshiamala"],
["D. Aramouni","Dimitri Aramouni"],
["D. Ferguson","Drew Ferguson"],
["D. Petrovic","Djordje Petrovic"],
["E Shrubsole","Ed Gribbons-Shrubsole"],
["E. Barzegar","Elbron Barzegar"],
["E. Koleosho","Emmanuel Koleosho"],
["E. Meredith","Eddie Meredith"],
["F Eveillard","Frednick Eveillard"],
["F Pankewich","Frank Pankewich"],
["G. Pallotto","Gabriel Pallotto"],
["G. Rapanaro","Giancarlo Rapanaro"],
["G. Trottier","Guillaume Trottier"],
["Guil. Masse","Guillaume Masse"],
["H. Beeforth","Harrison Beeforth"],
["H. da Costa","Harrison da Costa"],
["H. Finnikin","Horace Finnikin"],
["H. Hastings","Harland Hastings"],
["H. Mussotte","Hunter Mousseau"],
["I Frankovic","Ivo Frankovic"],
["I G.-Messam","Isaiah Guzylak-Messam"],
["I. Williams","Isaac Williams"],
["J Alexander","Josh Alexander"],
["J Andrushko","Justin Andrushko"],
["J Armstrong","Joshua Armstrong"],
["J Bokenfohr","Jackson Bokenfohr"],
["J Boutilier","Jordan Boutilier"],
["J Croasdale","Justis Croasdale"],
["J Hipperson","Jerimy Hipperson"],
["J Nicoletti","Jake Nicoletti"],
["J Sidsworth","Jordan Sidsworth"],
["J St. Louis","Jeffrey St Louis"],
["J Sutcliffe","Jordan Sutcliffe"],
["J-P Asselin","Jean-Philippe Asselin"],
["J. Beckford","Jahmeeks Beckford"],
["J. Cochrane","Josh Cochrane"],
["J. Dorocicz","Jonathan Dorocicz"],
["J. Hoolihan","Jordan Hoolihan"],
["J. Labenski","Joe Labenski"],
["J. Marriott","Jeremiah Marriott"],
["J. Matheson","John Matheson"],
["J. McMillan","Jordan McMillan"],
["J. Moynahan","John Moynahan"],
["J. Van Horn","Jordan Van Horn"],
["J. Williams","Josh Williams"],
["Jordan, Ben","Ben Jordan"],
["K. Amankwaa","Kingsley Amankwaa"],
["K. Mokenela","Kiamba Mokenela"],
["K.McCartney","Karl McCartney"],
["Kinkead, F.","Frederic Kinkead"],
["L McQuilkin","Luke McQuilkin"],
["Labbe, P L.","Pierre-Luc Labbe"],
["Labbe, P.L.","Pierre-Luc Labbe"],
["Lucyshyn,M.","Matthew Lucyshyn"],
["M Colangelo","Martin Colangelo"],
["M Dubuisson","Mike Dubuisson"],
["M Edgeworth","Matthew Edgeworth"],
["M Grandison","Marcus Grandison"],
["M Gruninger","Matt Gruninger"],
["M MacMillan","Matt McMillan"],
["M McDougall","Matthew McDougall"],
["M St. Aubin","Marcus St Aubin"],
["M St. aubin","Marcus St Aubin"],
["M. Domanico","Michael Domanico"],
["M. Lucyshyn","Matthew Lucyshyn"],
["M. Melansom","Max Melanson"],
["M. Melanson","Max Melanson"],
["M. Sheridan","Mark Sheridan"],
["M. St.Aubin","Marcus St Aubin"],
["Miller, Ian","Ian Miller"],
["Morrison, B","Blaise Morrison"],
["N D-Rodgers","Nicolas Diaquoi-Rodgers"],
["N Mirijello","Nicholas Mirijello"],
["N Shorthill","Nicholas Shortill"],
["N Zavarella","Nathan Zavarella"],
["N ZAVARELLA","Nathan Zavarella"],
["N. Cicchini","Nick Cicchini"],
["O. Oyebanji","Olaitan Oyebanji"],
["Onyeka Kene","Kene Onyeka"],
["R. Benjamin","Ryan Benjamin"],
["R. Labreque","Renaud Labrecque"],
["R. Lebreque","Renaud Labrecque"],
["Roberson, A","Alec Robertson"],
["S Ainsworth","Steven Ainsworth"],
["S Gauntlett","Stephen Gauntlett"],
["S LaMONagne","Simon Lamontagne"],
["S Tillotson","Sheldon Tillotson"],
["S Van Hende","Scott Van Hende"],
["S Zimmerman","Spencer Zimmerman"],
["S. Boroniec","Stephan Boroniec"],
["S. Bradbury","Spencer Bradbury"],
["S. Chambers","Shamawd Chambers"],
["S. da Costa","Spencer da Costa"],
["S. Guenette","Steven Guenette"],
["S. Reynolds","Sehkahnee Reynolds"],
["Spataro, M.","Mitchell Spataro"],
["T Bresciani","Thomas Bresciani"],
["T Calverley","Taylor Calverley"],
["T Chakwesha","Tanaka Chakwesha"],
["T Festeryga","Ted Festeryga"],
["T Pastusiak","Taylor Pastusiak"],
["T. Doughlin","Tristan Doughlin"],
["T. Ferenczy","Tristan Ferenczy"],
["T. Hercules","Tristan Hercules"],
["T. McGarity","Trevor McGarrity"],
["T. Narbaitz","Thomas Narbaitz"],
["T. Yaworski","Tyler Yaworski"],
["T.St.Pierre","Tyrone St Pierre"],
["Trottier,G.","Guillaume Trottier"],
["U. Levesque","Ugo Levesque"],
["U. LEVESQUE","Ugo Levesque"],
["W Bannatyne","Will Bannatyne"],
["W Wiltshire","Will Wiltshire"],
["W. Subranni","William Subranni"],
["Williams, S","Steve Williams"],
["Y L-Vanasse","Yannick Langelier-Vanasse"],
["A Baechler","Andy Baechler"],
["A Federico","Anthony Federico"],
["A Petrucci","Anthony Petrucci"],
["A. Bestard","Adam Bestard"],
["A. LOTHIAN","Alex Lothian"],
["A. Lothian","Alex Lothian"],
["A. Whonder","Akeem Whonder"],
["A.J. Allen","AJ Allen"],
["A.j. Allen","AJ Allen"],
["A.J. Chase","AJ Chase"],
["A.j. Chase","AJ Chase"],
["B Hamilton","Brett Hamilton"],
["B Kootstra","Bobby Kootstra"],
["B Lawrence","Blake Lawrence"],
["B Morrison","Blaise Morrison"],
["B Yohnicki","Brandon Yohnicki"],
["B. Nichols","Brendon Nichols"],
["B. Stearns","Byron Stearns"],
["B. Wheeler","Brent Wheeler"],
["B.Rockhill","Brandon Rockhill"],
["C Arquette","Chris Arquette"],
["C Farquhar","Chad Farquhar"],
["C Fernades","Cory Fernandes"],
["C Hastings","Cordell Hastings"],
["C Williams","Corey Williams"],
["C. Gervais","Chris Gervais"],
["D Di Carlo","Domenic Di Carlo"],
["D Ferguson","Drew Ferguson"],
["D Petrovic","Djordje Petrovic"],
["D Williams","Damone Williams"],
["D. Comtois","Dominique Comtois"],
["D. McBride","Dan McBride"],
["D. Oduwole","Deji Oduwole"],
["D. Skillen","David Skillen"],
["D. Timmons","David Timmons"],
["E Armitage","Eric Armitage"],
["E Buchanan","Evan Buchanan"],
["E Hewitson","Eric Hewitson"],
["E Kinnunen","Erik Kinnunen"],
["E Williams","Evan Williams"],
["E-J Maroun","Elie-Joseph Maroun"],
["E. Musangu","Emmanuel Musangu"],
["E. Nielsen","Erik Nielsen"],
["F. Kinkead","Frederic Kinkead"],
["F. Ngandui","Franck Ngandui"],
["F. NGANDUI","Franck Ngandui"],
["G Plumpton","Greg Plumpton"],
["G Rapanaro","Giancarlo Rapanaro"],
["G Schelske","Grant Schelske"],
["G. Harding","Gates Harding"],
["G. Sanvido","Garret Sanvido"],
["H Beeforth","Harrison Beeforth"],
["H da Costa","Harrison da Costa"],
["H Finnikin","Horace Finnikin"],
["H Hastings","Harland Hastings"],
["H Mutobola","Harold Mutobola"],
["H Principi","Hunter Principi"],
["H Tallyhoe","Harrison Tallyhoe"],
["I G-Messam","Isaiah Guzylak-Messam"],
["J Beaulieu","Jordan Beaulieu"],
["J Brecevic","Jeremy Brecevic"],
["J Buttrill","Josh Buttrill"],
["J Cobourne","Jordan Cobourne"],
["J Cordeiro","Jon Cordeiro"],
["J Hoolihan","Jordan Hoolihan"],
["J McAndrew","Josh McAndrew"],
["J McCoskey","Jordan McCoskey"],
["J McMillan","Jordan McMillan"],
["J Moynahan","John Moynahan"],
["J Mullings","Jamal Mullings"],
["J Raycroft","Jesse Raycroft"],
["J Storozok","Joe Storozok"],
["J Wood-Roy","Justin Wood-Roy"],
["J-G Poulin","Jean-Gabriel Poulin"],
["J. DesWLUs","JJ DesLauriers"],
["J. Hammond","Justin Hammond"],
["J. Langley","John Langley"],
["J. Leblanc","Julien Leblanc"],
["J. LeBlanc","Julien Leblanc"],
["J. Leggett","Jonathan Leggett"],
["J. Palardy","Justin Palardy"],
["J. Sifakis","James Sifakis"],
["J. Skillen","John Skillen"],
["J. Smeaton","Jeff Smeaton"],
["J. Wensley","Justin Wensley"],
["J.Cochrane","Josh Cochrane"],
["J.Hoolihan","Jordan Hoolihan"],
["J.McMillan","Jordan McMillan"],
["K Amankwaa","Kingsley Amankwaa"],
["K Chisholm","Kyle Chisholm"],
["K Silveyra","Kevin Silveyra"],
["K Williams","Kevin Williams"],
["K. Ankamah","Kendrick Ankamah"],
["K. Nkansah","Kwasi Nkansah"],
["Kinkead,F.","Frederic Kinkead"],
["Leeper, TJ","TJ Leeper"],
["M Atkinson","Mitchell Atkinson"],
["M Lucyshyn","Matthew Lucyshyn"],
["M MacIsaac","Marcus MacIsaac"],
["M Melanson","Max Melanson"],
["M Rutledge","Mark Rutledge"],
["M Sheridan","Mark Sheridan"],
["M St Aubin","Marcus St Aubin"],
["M St.aubin","Marcus St Aubin"],
["M-A Laurin","Marc-Antoine Laurin"],
["M. Alfonso","Mike Alfonso"],
["M. Griffin","Matt Griffin"],
["M. Kassner","Matt Kassner"],
["M. KASSNER","Matt Kassner"],
["M. Lindell","Marc Lindell"],
["M. Loggale","Mandella Loggale"],
["M. McGarva","Matt McGarva"],
["M. Montoya","Mike Montoya"],
["M. Spataro","Mitchell Spataro"],
["M. Tedesco","Mario Tedesco"],
["M.Melanson","Max Melanson"],
["Miklos MAC","Miklos McMaster"],
["N Baldassi","Nick Baldassi"],
["N Cicchini","Nick Cicchini"],
["N. Cameron","Nick Cameron"],
["N. Corrado","Nick Corrado"],
["N. Niforos","Nick Niforos"],
["N. Randall","Nick Randall"],
["N. Summach","Nick Summach"],
["P. Dominic","Peter Dominic"],
["P. Donovan","Pat Donovan"],
["P. Hancock","Paul Hancock"],
["P. Quinney","Peter Quinney"],
["P. Scherer","Phil Scherer"],
["P.L. Labbe","Pierre-Luc Labbe"],
["Poulin,J-G","Jean-Gabriel Poulin"],
["R Benjamin","Ryan Benjamin"],
["R Carnegie","Rob Carnegie"],
["R Hartmann","Raye Hartmann"],
["R Kovshoff","Joel Kovshoff"],
["R Veenstra","Richard Veenstra"],
["R Williams","Reid Williams"],
["R WILLIAMS","Reid Williams"],
["R. Nketiah","Richmond Nketiah"],
["R.Benjamin","Ryan Benjamin"],
["S Boroniec","Stephan Boroniec"],
["S Bradbury","Spencer Bradbury"],
["S Chambers","Shamawd Chambers"],
["S Guenette","Steven Guenette"],
["S Wiechert","Spencer Wiechert"],
["S Williams","Steve Williams"],
["S. Gladman","Sebastian Gladman"],
["S. Grimard","Simon Grimard"],
["S. Holness","Steven Holness"],
["S. Magalas","Sebastian Magalas"],
["S. O'Brien","Sean O'Brien"],
["S.Guenette","Steven Guenette"],
["Spataro,M.","Mitchell Spataro"],
["T Doughlin","Tristan Doughlin"],
["T Hercules","Tristan Hercules"],
["T Narbaitz","Thomas Narbaitz"],
["T Richards","Troy Richardson"],
["T Thibault","Tyler Thibault"],
["U Levesque","Ugo Levesque"],
["U. Nwaesei","Udoka Nwaesei"],
["W Robinson","Wes Robinson"],
["W Subranni","William Subranni"],
["W. DeSouza","Wilkerson DeSouza"],
["Y. Dalloul","Yahia Dalloul"],
["Y. Dalluol","Yahia Dalloul"],
["Z Fitterer","Zach Fitterer"],
["A Daprato","Alex Daprato"],
["A Marcoux","Alexandre Marcoux"],
["A MARCOUX","Alexandre Marcoux"],
["A Wheaton","Aaron Wheaton"],
["A Whonder","Akeem Whonder"],
["A. Capson","Alex Capson"],
["A. Foster","Akeem Foster"],
["A. Lavres","Arnoldo Lavres"],
["A. LAVRES","Arnoldo Lavres"],
["A. Lowery","Andrew Lowery"],
["B Backman","Brett Backman"],
["B Wheeler","Brent Wheeler"],
["B. Devlin","Brian Devlin"],
["B. Hinton","Brad Hinton"],
["B. Landry","Beau Landry"],
["B. Martin","Brett Martin"],
["B. Taylor","Brad Taylor"],
["B. Willan","Bjay Willan"],
["BECK,JOHN","John Beck"],
["C Andrews","Colin Andrews"],
["C Wilhelm","Cameron Wilhelm"],
["C. Deneau","Chris Deneau"],
["C. Murphy","Corey Murphy"],
["C. Plante","Christian Plante"],
["C. PLANTE","Christian Plante"],
["C. Ridley","Christian Ridley"],
["C.Gervais","Chris Gervais"],
["D Crowder","Dustin Crowder"],
["D Dicarlo","Domenic Di Carlo"],
["D DiCarlo","Domenic Di Carlo"],
["D Luciani","Dante Luciani"],
["D Sheahan","Devan Sheahan"],
["D Skillen","David Skillen"],
["D. Benson","Daniel Benson"],
["D. Hayman","Dustin Hayman"],
["D. Levell","David Levell"],
["D. MONoya","Dave Montoya"],
["D. Schulz","Dustin Schulz"],
["D.Oduwole","Deji Oduwole"],
["D.Skillen","David Skillen"],
["DJ Sackey","DJ Sackey"],
["E McNally","Ed McNally"],
["E Musangu","Emmanuel Musangu"],
["E Nielsen","Erik Nielsen"],
["E. BROOKS","Errol Brooks"],
["E. Hughes","Evan Hughes"],
["E. Renaud","Eric Renaud"],
["E. RENAUD","Eric Renaud"],
["E.Nielsen","Erik Nielsen"],
["F Kinkead","Frederic Kinkead"],
["F Ngandui","Franck Ngandui"],
["F NGANDUI","Franck Ngandui"],
["G Boucher","Gabriel Boucher"],
["G Sandivo","Garret Sanvido"],
["G Sanvido","Garret Sanvido"],
["G Willson","Greg Willson"],
["G. Bayley","Gresham Bayley"],
["J Buckley","Javier Buckley"],
["J Cornett","Jack Cornett"],
["J Cortese","Joseph Cortese"],
["J DesWLUs","JJ DesLauriers"],
["J Fioroni","James Fioroni"],
["J Hammond","Justin Hammond"],
["J Holland","Justin Holland"],
["J Langley","John Langley"],
["J Radford","Jeff Radford"],
["J Ratazzi","Joey Rattazzi"],
["J Russell","Jordan Russell"],
["J Sifakis","James Sifakis"],
["J Skillen","John Skillen"],
["J Tritler","Joe Tritler"],
["J Widgett","Jonathan Widgett"],
["J Willard","Joseph Willard"],
["J Woodman","Josh Woodman"],
["J-P Hudon","Jean-Philippe Hudon"],
["J. Barnes","Joe Barnes"],
["J. Brooks","Jeff Brooks"],
["J. Darius","Jamal Darius"],
["J. Hachey","Jay Hachey"],
["J. Langma","Jonathan Langma"],
["J. Lavoie","Jacob Lavoie"],
["J. Melnyk","Jared Melnyk"],
["J. Murray","John Murray"],
["J. Wright","Joel Wright"],
["J.Edwards","Justene Edwards"],
["J.Skillen","John Skillen"],
["K Nkansah","Kwasi Nkansah"],
["K. Ardill","Kyle Ardill"],
["K.Nkansah","Kwasi Nkansah"],
["L. Bendus","Luke Bendus"],
["L. Demers","Logan Demers"],
["L. Pinder","Luke Pinder"],
["L. Shaver","Lee Shaver"],
["L. Thomas","Luke Thomas"],
["M Alfonso","Mike Alfonso"],
["M Borucki","Marek Borucki"],
["M Bucknor","Matt Bucknor"],
["M Fortino","Mike Fortino"],
["M Gabrick","Matt Gabrick"],
["M Johnson","Mason Johnson"],
["M KASSNER","Matt Kassner"],
["M Kassner","Matt Kassner"],
["M Lindell","Marc Lindell"],
["M Loggale","Mandella Loggale"],
["M Maurice","Michael Maurice"],
["M McGarva","Matt McGarva"],
["M McIsaac","Marcus MacIsaac"],
["M Montoya","Mike Montoya"],
["M Ritchie","Matt Ritchie"],
["M Spataro","Mitchell Spataro"],
["M Tedesco","Mario Tedesco"],
["M Whaling","Mike Whaling"],
["M. Bolduc","Mathew Bolduc"],
["M. Cahill","Mike Cahill"],
["M. Dender","Mitch Dender"],
["M. Gordon","Marty Gordon"],
["M. Graham","Mitchell Graham"],
["M. Picton","Mitchell Picton"],
["M. Santos","Matt Santos"],
["M. Sealey","McCartney Sealey"],
["M.Donovan","Mickey Donovan"],
["M.Griffin","Matt Griffin"],
["M.Kassner","Matt Kassner"],
["Marino, A","Anthony Marino"],
["N Cameron","Nick Cameron"],
["N Corrado","Nick Corrado"],
["N Niforos","Nick Niforos"],
["N. Conway","Nathan Conway"],
["N. Durkan","Nathanael Durkan"],
["N. Fermin","Nathaniel Fermin"],
["N. Taylor","Nick Taylor"],
["O Onayemi","Oladipo Onayemi"],
["O Ukwuoma","Osie Ukwuoma"],
["P Donovan","Pat Donovan"],
["P Hancock","Paul Hancock"],
["P Huggins","Preston Huggins"],
["P Quinney","Peter Quinney"],
["P. Brunet","Patrick Brunet"],
["P. Morgan","Peter Morgan"],
["P. Sibley","Paul Sibley"],
["P.Donovan","Pat Donovan"],
["P.L Labbe","Pierre-Luc Labbe"],
["P.L.Labbe","Pierre-Luc Labbe"],
["R MONSOUR","Ramon Monsour"],
["R Nketiah","Richmond Nketiah"],
["R. ALMONE","Roberto Almonte"],
["R. AlMONe","Roberto Almonte"],
["R. Connop","Rory Connop"],
["R. O'Shea","Rob O'Shea"],
["S Charles","Stefan Charles"],
["S Magalas","Sebastian Magalas"],
["S Mouawad","Samir Mouawad"],
["S O'Brien","Sean O'Brien"],
["S. Dupuis","Stefan Dupuis"],
["S. Fraser","Salim Fraser"],
["S. KETEKU","Sheldon Keteku"],
["S. Munroe","Shaquille Munroe"],
["S.O'Brien","Sean O'Brien"],
["T Abraham","Theo Abraham"],
["T Griffin","Tanner Griffin"],
["T Lammers","Tomas Lammers"],
["T Mauldin","Terry Mauldin"],
["T SHEgold","Taylor Shergold"],
["T Vaughan","Travis Vaughan"],
["T. Bailey","Tom Bailey"],
["T. Blight","Thomas Blight"],
["T. Packer","Tyler Packer"],
["T. Sawyer","Tyler Sawyer"],
["T. SAWYER","Tyler Sawyer"],
["T. Thomas","Terell Thomas"],
["U Nwaesei","Udoka Nwaesei"],
["V Frasson","Vincenzo Frasson"],
["V. Flamia","Vince Flamia"],
["W Desmond","Wayne Desmond"],
["W DeSouza","Wilkerson DeSouza"],
["W. Conrad","Wade Conrad"],
["Y Dalloul","Yahia Dalloul"],
["Y.Dalloul","Yahia Dalloul"],
["Y.Dalluol","Yahia Dalloul"],
["Z Elsayed","Ziad Elsayed"],
["Z. Miller","Zach Miller"],
["Z. Raynor","Zach Raynor"],
["Z. RAYNOR","Zach Raynor"],
["A Dandie","Anthony Dandie"],
["A Dolley","Adrian Dolley"],
["A Foster","Akeem Foster"],
["A Lowery","Andrew Lowery"],
["A Marino","Anthony Marino"],
["A. Sayer","Aaron Sayer"],
["A.Capson","Alex Capson"],
["A.Houwer","Adrian Houwer"],
["A.Lowery","Andrew Lowery"],
["B Landry","Beau Landry"],
["B Martin","Brett Martin"],
["B Mokube","Brittley Mokube"],
["B Stoker","Brandon Stoker"],
["B Taylor","Brad Taylor"],
["B. Sitch","Brad Sich"],
["C Deneau","Chris Deneau"],
["C Moynes","Cody Moynes"],
["C Murphy","Corey Murphy"],
["C Plante","Christian Plante"],
["C Ridley","Christian Ridley"],
["C Rushon","Craig Rushon"],
["C Schell","Connor Schell"],
["C Walden","Cordelle Walden"],
["C Walker","Cam Walker"],
["C Wihelm","Cameron Wilhelm"],
["C Wright","Casey Wright"],
["C. Bince","Corey Bince"],
["C. Burke","Connor Burke"],
["C. Kitts","CJ Kitts"],
["C. Magno","Chris Magno"],
["C. Smith","Cam Smith"],
["C. Wicks","Colin Wicks"],
["C.Murphy","Corey Murphy"],
["D Benson","Daniel Benson"],
["D Cossar","Dylan Cossar"],
["D Hansen","Dane Hansen"],
["D Hymers","Derek Hymers"],
["D Levell","David Levell"],
["D MONoya","Dave Montoya"],
["D Morris","Drew Morris"],
["D Munroe","Dorian Munroe"],
["D Petrin","Dylan Petrin"],
["D. Brown","David Brown"],
["D. Janic","Djordje Janic"],
["D. Weber","Dan Weber"],
["Dakota B","Dakota Brush"],
["E Brooks","Errol Brooks"],
["E BROOKS","Errol Brooks"],
["E Causer","Ejaz Causer"],
["E Hughes","Evan Hughes"],
["E Renaud","Eric Renaud"],
["E RENAUD","Eric Renaud"],
["G Jewson","Graham Jewson"],
["G.Bayley","Gresham Bayley"],
["H Bowman","Hunter Bowman"],
["H Muamba","Henoc Muamba"],
["H. Lopez","Hugo Lopez"],
["I. Logan","Ian Logan"],
["J Andric","Jordyn Andric"],
["J Barnes","Joe Barnes"],
["J Bowman","Justin Bowman"],
["J Brooks","Jeff Brooks"],
["J Currie","Jared Currie"],
["J Darius","Jamal Darius"],
["J Duncan","Jamie Duncan"],
["J Lavoie","Jacob Lavoie"],
["J Legris","JC Legris"],
["J Murray","John Murray"],
["J Tropea","Julian Tropea"],
["J Wilson","John Wilson"],
["J Wright","Joel Wright"],
["J. Beach","Jack Beach"],
["J. Daley","Jared Daley"],
["J. GESSE","Jacob Gesse"],
["J. Onomo","Joey Onomo"],
["J. Rojas","Juan Rojas"],
["K Ardill","Kyle Ardill"],
["K Cherry","Keiler Cherry"],
["K Lagace","Keith Lagace"],
["K Mataya","Kyle Mataya"],
["K Seilis","Kalven Seilis"],
["K Spratt","Keaton Spratt"],
["K Wasson","Kyle Wasson"],
["K. Asare","Kevin Asare"],
["K. Dugas","Keith Dugas"],
["K. Magee","Kevin Magee"],
["L Gordon","Larry Gordon"],
["L Shaver","Lee Shaver"],
["M Bolduc","Mathew Bolduc"],
["M Cahill","Mike Cahill"],
["M Dender","Mitch Dender"],
["M Fidani","Mark Fidani"],
["M Gordon","Marty Gordon"],
["M Hooper","Mitchell Hooper"],
["M Miller","Mike Miller"],
["M Picton","Mitchell Picton"],
["M Santos","Matt Santos"],
["M Suzuki","Matthew Suzuki"],
["M. Pesek","Martin Pesek"],
["M. Riggi","Mark Riggi"],
["M.Cahill","Mike Cahill"],
["M.Lavoie","Morgan Lavoie"],
["N Durkan","Nathanael Durkan"],
["N Fermin","Nathaniel Fermin"],
["N Hawkes","Nathan Hawkes"],
["N Rempel","Nicholas Rempel"],
["N. Dawes","Nate Dawes"],
["P Brunet","Patrick Brunet"],
["P Pankow","Patrick Pankow"],
["P Ramsay","Patrick Ramsay"],
["P. Ziter","Pat Ziter"],
["R ALMONE","Roberto Almonte"],
["R AUCOIN","Ryan Aucoin"],
["R Mahler","Rhys Mahler"],
["R O'Shea","Rob O'Shea"],
["R Penner","Reilly Penner"],
["R. Brown","Ryan Brown"],
["R. Hobbs","Ryan Hobbs"],
["R. Lynch","Ryan Lynch"],
["R. Olsen","Ryan Olsen"],
["R. Payne","Robert Payne"],
["R. PAYNE","Robert Payne"],
["S Dinner","Steve Dinner"],
["S Howard","Sebastian Howard"],
["S Lagace","Steve Lagace"],
["S Munroe","Shaquille Munroe"],
["S Stoqua","Sean Stoqua"],
["T Harvey","Trevor Harvey"],
["T MACann","Tyson McMann"],
["T McMann","Tyson McMann"],
["T Nguyen","Te Nguyen"],
["T RUZNAK","Ty Rusznak"],
["T SAWYER","Tyler Sawyer"],
["W Austin","Wes Austin"],
["W.Conrad","Wade Conrad"],
["X. Hasko","Xhejsi Hasko"],
["Z Miller","Zach Miller"],
["Z Raynor","Zach Raynor"],
["Z RAYNOR","Zach Raynor"],
["Z Scotto","Zach Scotto"],
["A Masur","Adam Masur"],
["A Mizan","Asante Mizan"],
["A Parle","Avery Parle"],
["A. Cole","Aaron Cole"],
["A. King","Aaron King"],
["A. Rowe","Andrew Rowe"],
["B Hines","Bryce Hines"],
["B. Keks","Brandon Keks"],
["B. Lowe","Brandon Lowe"],
["B. RAIC","Bogdan Raic"],
["B. Raic","Bogdan Raic"],
["C Allen","Cory Allen"],
["C Bince","Corey Bince"],
["C Cowan","Chris Cowan"],
["C Fryer","Cameron Fryer"],
["C Kitts","CJ Kitts"],
["C Magno","Chris Magno"],
["C Moore","Chase Moore"],
["C Scala","Carmen Scala"],
["C Smith","Cam Smith"],
["C. Daly","Chris Daly"],
["C. DALY","Chris Daly"],
["C. Mims","Calvin Mims"],
["D Brown","David Brown"],
["D Crane","David Crane"],
["D Stala","Dave Stala"],
["D Tiede","David Tiede"],
["D. Waud","Daryl Waud"],
["D.Jones","Dylan Jones"],
["D.Smith","Derek Smith"],
["E David","Ebun David"],
["E Roque","Eric Roque"],
["E Short","Evan Short"],
["G Smyth","Graham Smyth"],
["G. Cond","Gavin Cond"],
["H Lopez","Hugo Lopez"],
["H SHORT","Harry Short"],
["I Logan","Ian Logan"],
["I Noble","Ian Noble"],
["J Baird","Josh Baird"],
["J Hough","Jordan Hough"],
["J ONOMO","Joey Onomo"],
["J Perry","Joshua Perry"],
["J Tiede","Josh Tiede"],
["J. Bada","James Bada"],
["J. Ross","Josh Ross"],
["J.Price","Jalen Price"],
["K Adjei","Kwame Adjei"],
["K Grant","Kyle Grant"],
["M Brown","Matt Brown"],
["M David","Mason David"],
["M Jones","Mack Jones"],
["M Riggi","Mark Riggi"],
["M. Pham","Matt Pham"],
["M. Todd","Matt Todd"],
["N Annan","Nate Annan"],
["N Henry","Nigel Henry"],
["N Pinto","Nathaniel Pinto"],
["N Vanin","Nick Vanin"],
["N. Both","Nial Both"],
["P Kruba","Pawel Kruba"],
["R Henry","Rochae Henry"],
["R Lynch","Ryan Lynch"],
["R Madan","Rahul Madan"],
["R Olsen","Ryan Olsen"],
["R Omara","Ron Omara"],
["R Payne","Robert Payne"],
["R PAYNE","Robert Payne"],
["R.PAYNE","Robert Payne"],
["S Grant","Sean Grant"],
["S Lubin","Sterve Lubin"],
["S Pilon","Sebastien Pilon"],
["S Sarfo","Sylvester Sarfo"],
["S Watts","Steven Watts"],
["S.Sarfo","Sylvester Sarfo"],
["S.Watts","Steven Watts"],
["T Berta","Tim Berta"],
["T Brown","Tyler Brown"],
["T Huang","Thomas Huang"],
["T Kirby","Taylor Kidby"],
["T Lynch","Tom Lynch"],
["T. Dawe","Tyler Dawe"],
["T. Hart","Terry Hart"],
["T. Lass","Trevor Lass"],
["T. Reid","Tyrel Reid"],
["T. Seal","Trevor Seal"],
["T. SEAL","Trevor Seal"],
["W Green","Will Green"],
["W Scott","Will Scott"],
["W. Gray","Wyatt Gray"],
["X Hasko","Xhejsi Hasko"],
["A Cole","Aaron Cole"],
["A Haid","Aaron Haid"],
["A King","Aaron King"],
["A Rich","Addison Rich"],
["A Rowe","Andrew Rowe"],
["A. Fay","Aidan Fay"],
["A. Maj","Alex Maj"],
["A.King","Aaron King"],
["B Bell","Bryce Bell"],
["B Cook","Bryan Cook"],
["B RAIC","Bogdan Raic"],
["B Raic","Bogdan Raic"],
["B.Keks","Brandon Keks"],
["C Cull","Chris Cull"],
["C Daly","Chris Daly"],
["C DALY","Chris Daly"],
["C Fort","Chaney Fort"],
["C GOOD","Curtis Good"],
["C Gray","Cal Gray"],
["C Mims","Calvin Mims"],
["C Moen","Connor Moen"],
["C.Mims","Calvin Mims"],
["D John","Dylan John"],
["D Waud","Daryl Waud"],
["D. Cox","Derek Cox"],
["Dent,M","Michael Dent"],
["G Cond","Gavin Cond"],
["G Post","Garrit Post"],
["H Mair","Harrison Mair"],
["J BECK","John Beck"],
["J Beck","John Beck"],
["J Tait","Joshua Tait"],
["J Woof","Jarrett Woof"],
["J. BIS","Josh Bishop"],
["J.Hood","Jonathan Hood"],
["J.Ross","Josh Ross"],
["John R","John Rush"],
["L Noel","Llevi Noel"],
["L Reda","Luke Reda"],
["L Ward","Lewis Ward"],
["M Peto","Matt Peto"],
["M Pham","Matt Pham"],
["M Reid","Mykal Reid"],
["M Todd","Matt Todd"],
["M Vonk","Matt Vonk"],
["M. Fox","Makenzie Fox"],
["P Gany","Pabek Gany"],
["S Odum","Sydney Odum"],
["S Ples","Steven Ples"],
["T Bach","Taylor Bach"],
["T Hart","Terry Hart"],
["T Lass","Trevor Lass"],
["T Reid","Tyrel Reid"],
["T SEAL","Trevor Seal"],
["T Seal","Trevor Seal"]]